--CREATE DATABASE
CREATE DATABASE QuanlyVe;
--
GO
USE QuanLyVe;
--
GO
CREATE TABLE HOADON(
	M_HĐ CHAR(10) NOT NULL,
	M_VE CHAR(10),
	NGAY_LAP_HĐ DATE,
	M_PHIM CHAR(10),
	MKH CHAR(10),
	M_RAP CHAR(10),
	NCHAR(10),
	M_PC NCHAR(10),
	M_NV NCHAR(10),
	TG_LAP_HĐ TIME

)
ALTER TABLE HOADON
ADD CONSTRAINT PK_HOADON
PRIMARY KEY (M_HĐ)
GO
CREATE TABLE KHACHHANG(
MKH CHAR(10) NOT NULL,
TEN_KH NVARCHAR(50),
DIA_CHI NCHAR(100),
SDT CHAR(12),
EMAIL CHAR(40),
HINH_THUC_THANH_TOAN CHAR(10)
)
ALTER TABLE KHACHHANG
ADD CONSTRAINT PK_KHACHHANG
PRIMARY KEY (MKH)

--FOREIGN
ALTER TABLE HOADON
ADD CONSTRAINT PK_KHACHHANG_HOADON
FOREIGN KEY (MKH) REFERENCES KHACHHANG(MKH)


GO
CREATE TABLE VE(
M_VE CHAR(10) NOT NULL,
TEN_LOAI NCHAR(10),
GIA_VE INT,
LOAI_CHO_NGOI NCHAR(10),
LOAI_PHIM NCHAR(10),
SO_LUONG INT
)
ALTER TABLE VE
ADD CONSTRAINT PK_VE
PRIMARY KEY (M_VE)

--FOREIGN
ALTER TABLE HOADON
ADD CONSTRAINT PK_VE_HOADON
FOREIGN KEY (M_VE) REFERENCES VE(M_VE)

GO
CREATE TABLE PHIM(
M_PHIM CHAR(10) NOT NULL,
TEN_PHIM NCHAR(40),
HSX NCHAR(40),
THOI_LUONG TIME,
DAO_DIEN NCHAR(30),
THE_LOAI NCHAR(30)
)
ALTER TABLE PHIM
ADD CONSTRAINT PK_PHIM
PRIMARY KEY (M_PHIM)

--FOREIGN
ALTER TABLE HOADON
ADD CONSTRAINT PK_PHIM_HOADON
FOREIGN KEY (M_PHIM) REFERENCES PHIM(M_PHIM)

GO
CREATE TABLE RAPCHIEU(
M_RAP CHAR(10) NOT NULL,
TEN_RAP NCHAR(30),
DIA_CHI NCHAR(100),
SĐT NCHAR(12)
)

ALTER TABLE RAPCHIEU
ADD CONSTRAINT PK_RAPCHIEU
PRIMARY KEY (M_RAP)

--FOREIGN
ALTER TABLE HOADON
ADD CONSTRAINT PK_RAPCHIEU_HOADON
FOREIGN KEY (M_RAP) REFERENCES RAPCHIEU(M_RAP)

GO
CREATE TABLE PHONGCHIEU(
M_PC NCHAR(10) NOT NULL,
TEN_PC CHAR(10),
SO_CHO CHAR(10),
MAY_CHIEU_LOAI NCHAR(10),
AM_THANH_LOAI NCHAR(10)
)
ALTER TABLE PHONGCHIEU
ADD CONSTRAINT PK_PHONGCHIEU
PRIMARY KEY (M_PC)

--FOREIGN
ALTER TABLE HOADON
ADD CONSTRAINT PK_PHONGCHIEU_HOADON
FOREIGN KEY (M_PC) REFERENCES PHONGCHIEU(M_PC)

GO

CREATE TABLE NHANVIEN(
M_NV NCHAR(10) NOT NULL,
TEN_NV NCHAR(30),
NGAY_SINH DATE,
PHAI NCHAR(10),
SĐT NCHAR(12)

)
ALTER TABLE NHANVIEN
ADD CONSTRAINT PK_NHANVIEN
PRIMARY KEY (M_NV)

--FOREIGN
ALTER TABLE HOADON
ADD CONSTRAINT PK_NHANVIEN_HOADON
FOREIGN KEY (M_NV) REFERENCES NHANVIEN(M_NV)
GO
CREATE TABLE LICHCHIEU(
M_LC NCHAR(10) NOT NULL,
TEN_PHIM NCHAR(40),
CA_CHIEU NCHAR(10)



)
ALTER TABLE LICHCHIEU
ADD CONSTRAINT PK_LICHCHIEU
PRIMARY KEY (M_LC)

--FOREIGN
ALTER TABLE HOADON
ADD CONSTRAINT PK_LICHCHIEU_HOADON
FOREIGN KEY (M_LC) REFERENCES LICHCHIEU(M_LC) 
GO
SELECT *
FROM PHIM
WHERE HSX='WANNER'
GO
SELECT *
FROM PHIM
WHERE THE_LOAI='TIEU THUYET'
GO
SELECT TEN_PHIM
FROM PHIM
WHERE HSX='20THCENT' AND THE_LOAI='HANH DONG'
GO
SELECT *
FROM HOADON
WHERE M_PHIM='MP03'

GO
SELECT M_HĐ
FROM HOADON
WHERE M_RAP='MR06' UNION 
SELECT M_HĐ FROM HOADON WHERE M_PC='PC04'
GO
SELECT M_HĐ
FROM HOADON
WHERE M_NV='NV05'
GO
SELECT TEN_KH 
FROM HOADON, KHACHHANG
WHERE HOADON.MKH=KHACHHANG.MKH AND M_HĐ='HD02'
GO
SELECT *
FROM KHACHHANG
WHERE MKH='KH04'
GO
SELECT MKH
FROM HOADON
WHERE NGAY_LAP_HĐ='2019-11-24'
GO
SELECT *
FROM VE
WHERE GIA_VE>90000
GO
SELECT TEN_PC
FROM PHONGCHIEU
WHERE SO_CHO>200
GO
SELECT TEN_PC
FROM PHONGCHIEU
WHERE MAY_CHIEU_LOAI='A' AND AM_THANH_LOAI='A'
GO
SELECT TEN_PHIM
FROM LICHCHIEU
WHERE CA_CHIEU='CHIEU'
GO
SELECT TEN_RAP
FROM RAPCHIEU
WHERE M_RAP='MR04'
GO
SELECT M_PHIM
FROM HOADON, RAPCHIEU
WHERE RAPCHIEU.M_RAP=HOADON.M_RAP AND SĐT='02873008881'
GO

